services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ArticleInsert\:
    resource: ../../
    exclude: ../../{DependencyInjection,Resources,Tests}

  ArticleInsert\Controller\:
    resource: ../../Controller
    tags: ['controller.service_arguments']
    public: true
